export const tempoMarkings = [
  { term: "Larghissimo", bpmMin: 10, bpmMax: 24, description: "Extremely slow, almost static", musicalFeel: "Funereal, meditative, immense space" },
  { term: "Grave", bpmMin: 25, bpmMax: 45, description: "Very slow and solemn", musicalFeel: "Heavy, serious, weighty" },
  { term: "Largo", bpmMin: 40, bpmMax: 60, description: "Broad and dignified", musicalFeel: "Expansive, flowing, majestic" },
  { term: "Larghetto", bpmMin: 60, bpmMax: 66, description: "Rather broad, slightly faster than Largo", musicalFeel: "Intimate, gentle, floating" },
  { term: "Adagio", bpmMin: 66, bpmMax: 76, description: "Slow and stately", musicalFeel: "Lyrical, expressive, breathing" },
  { term: "Adagietto", bpmMin: 70, bpmMax: 80, description: "Quite slow, slightly faster than Adagio", musicalFeel: "Intimate, softer, gentle" },
  { term: "Andante", bpmMin: 76, bpmMax: 108, description: "At a walking pace", musicalFeel: "Natural, unhurried, steady" },
  { term: "Andantino", bpmMin: 80, bpmMax: 108, description: "Slightly faster than Andante", musicalFeel: "Flowing, lighter, moving" },
  { term: "Moderato", bpmMin: 108, bpmMax: 120, description: "Moderate tempo", musicalFeel: "Balanced, controlled, neutral" },
  { term: "Allegretto", bpmMin: 112, bpmMax: 120, description: "Moderately fast", musicalFeel: "Lively but relaxed, playful" },
  { term: "Allegro", bpmMin: 120, bpmMax: 168, description: "Fast, quick, and bright", musicalFeel: "Energetic, joyful, animated" },
  { term: "Vivace", bpmMin: 168, bpmMax: 176, description: "Lively and fast", musicalFeel: "Brilliant, sparkling, spirited" },
  { term: "Vivacissimo", bpmMin: 172, bpmMax: 176, description: "Very lively, faster than Vivace", musicalFeel: "Intense, fiery, urgent" },
  { term: "Allegrissimo", bpmMin: 172, bpmMax: 176, description: "Very fast, faster than Allegro", musicalFeel: "Exciting, brilliant, rapid" },
  { term: "Presto", bpmMin: 168, bpmMax: 200, description: "Very fast", musicalFeel: "Exciting, breathless, driving" },
  { term: "Prestissimo", bpmMin: 200, bpmMax: 300, description: "Extremely fast (as fast as possible)", musicalFeel: "Explosive, frantic, virtuosic" },
]
