export const tempoMarkings = [
  { term: "Larghissimo", bpmMin: 10, bpmMax: 20, description: "Extremely slow, almost static", musicalFeel: "Funereal, meditative, immense space" },
  { term: "Grave", bpmMin: 20, bpmMax: 40, description: "Very slow and solemn", musicalFeel: "Heavy, serious, weighty" },
  { term: "Lento", bpmMin: 40, bpmMax: 45, description: "Slow", musicalFeel: "Relaxed, floating, spacious" },
  { term: "Largo", bpmMin: 45, bpmMax: 50, description: "Broad and dignified", musicalFeel: "Expansive, flowing, majestic" },
  { term: "Adagio", bpmMin: 55, bpmMax: 65, description: "Slow and stately", musicalFeel: "Lyrical, expressive, breathing" },
  { term: "Adagietto", bpmMin: 65, bpmMax: 69, description: "Quite slow, slightly faster than Adagio", musicalFeel: "Intimate, softer, gentle" },
  { term: "Andante", bpmMin: 73, bpmMax: 77, description: "At a walking pace", musicalFeel: "Natural, unhurried, steady" },
  { term: "Andantino", bpmMin: 78, bpmMax: 83, description: "Slightly faster than Andante", musicalFeel: "Flowing, lighter, moving" },
  { term: "Moderato", bpmMin: 108, bpmMax: 120, description: "Moderate tempo", musicalFeel: "Balanced, controlled, neutral" },
  { term: "Allegretto", bpmMin: 100, bpmMax: 110, description: "Moderately fast", musicalFeel: "Lively but relaxed, playful" },
  { term: "Allegro", bpmMin: 120, bpmMax: 140, description: "Fast, quick, and bright", musicalFeel: "Energetic, joyful, animated" },
  { term: "Vivace", bpmMin: 140, bpmMax: 160, description: "Lively and fast", musicalFeel: "Brilliant, sparkling, spirited" },
  { term: "Presto", bpmMin: 168, bpmMax: 200, description: "Very fast", musicalFeel: "Exciting, breathless, driving" },
  { term: "Prestissimo", bpmMin: 200, bpmMax: 300, description: "Extremely fast (as fast as possible)", musicalFeel: "Explosive, frantic, virtuosic" },
]
